# Change these first
owner: DARKDRAGON-LK # Your GitHub organization or username, where this repository lives
repo: ServerMonitor # The name of this repository

sites:
  - name: Coop
    url: https://coop.carecode.org
  - name: Southern Lanka
    url: https://southernlanka.carecode.org
  - name: Ruhunu 
    url: https://rh.carecode.org
  - name: Ruhunu Medi House
    url: https://rmh.carecode.org
  - name: Digasiri
    url: https://digasiri.carecode.org
  - name: Mathara Pharmacy
    url: https://mp.carecode.org
  - name: Engage Wellness Center
    url: https://ewc.carecode.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /ServerMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CareCode Server Details
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
commitMessages:
  commitAuthorName: "Lawan Chaamindu"
  commitAuthorEmail: "lawan.chaamindu1234@gmail.com"
